"""Phase 3: card, card_state, review_log, app_state

Revision ID: b74ed7d5e966
Revises:
Create Date: 2026-08-28 18:04:23.372239

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel renders string columns as sqlmodel.sql.sqltypes.AutoString(),
# so autogenerated migrations need this import to run.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b74ed7d5e966"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appstate",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offset_days", sa.Integer(), nullable=False),
        sa.Column("language_filter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appstate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_appstate_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_appstate_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "card",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("card_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("direction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("card_id"),
    )
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_card_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_card_language"), ["language"], unique=False)
        batch_op.create_index(batch_op.f("ix_card_reference"), ["reference"], unique=False)
        batch_op.create_index(batch_op.f("ix_card_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "cardstate",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("card_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("box", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.card_id"],
        ),
        sa.PrimaryKeyConstraint("card_id"),
    )
    with op.batch_alter_table("cardstate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cardstate_box"), ["box"], unique=False)
        batch_op.create_index(batch_op.f("ix_cardstate_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_cardstate_due_date"), ["due_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_cardstate_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "reviewlog",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewed_on", sa.Date(), nullable=False),
        sa.Column("grade", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("box_before", sa.Integer(), nullable=False),
        sa.Column("box_after", sa.Integer(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("answer_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("verdict_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("matched", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.card_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviewlog", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviewlog_card_id"), ["card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviewlog_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviewlog_reviewed_on"), ["reviewed_on"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviewlog_updated_at"), ["updated_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviewlog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviewlog_updated_at"))
        batch_op.drop_index(batch_op.f("ix_reviewlog_reviewed_on"))
        batch_op.drop_index(batch_op.f("ix_reviewlog_deleted"))
        batch_op.drop_index(batch_op.f("ix_reviewlog_card_id"))

    op.drop_table("reviewlog")
    with op.batch_alter_table("cardstate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cardstate_updated_at"))
        batch_op.drop_index(batch_op.f("ix_cardstate_due_date"))
        batch_op.drop_index(batch_op.f("ix_cardstate_deleted"))
        batch_op.drop_index(batch_op.f("ix_cardstate_box"))

    op.drop_table("cardstate")
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_card_updated_at"))
        batch_op.drop_index(batch_op.f("ix_card_reference"))
        batch_op.drop_index(batch_op.f("ix_card_language"))
        batch_op.drop_index(batch_op.f("ix_card_deleted"))

    op.drop_table("card")
    with op.batch_alter_table("appstate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appstate_updated_at"))
        batch_op.drop_index(batch_op.f("ix_appstate_deleted"))

    op.drop_table("appstate")
    # ### end Alembic commands ###
